server.port=8080
spring.application.name=predictive-hazard-alerter
spring.jackson.serialization.write-dates-as-timestamps=false
ors.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImE0NDZiNzgyMDVlYzQ4ODk5ZGNkYWVkNDBkMmM2NzgxIiwiaCI6Im11cm11cjY0In0=
ors.api.url=https://api.openrouteservice.org/v2/directions/driving-car
nominatim.api.url=https://nominatim.openstreetmap.org/search
